# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [labeled]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  addissue:
    name: Add issue to project

    # PR must must be merged, not closed
    if: github.event.pull_request.merged
    
    runs-on: ubuntu-20.04

    steps:
      - name: Add to Project
        run: |
          curl --request POST \
          --url https://github.com/apkendall10/NBADFS/projects/1#column-14500932 \
          --header "Accept: application/vnd.github.inertia-preview+json" \
          --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          --data '{"content_id": ${{ github.event.issue.id }}, "content_type": "Issue"}'
